version: "3"

services:
  anakonda:
    build: .
    image: anakonda:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - 8080/tcp
    networks:
      - edge
      - db
# Application goes behind external load balancer.
# Enable port to debug locally.
#    ports:
#      - 8080:8080/tcp

  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    expose:
      - 3306/tcp
    networks:
      - db
    volumes:
      - mysqldata:/var/lib/mysql

networks:
  edge:
    external: true
  db:

volumes:
  mysqldata:
